server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://accountdbprod:5433/accountdbprod
    username: admin
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://crmdiscoveryserver:9000/eureka/
    register-with-eureka: true
    fetch-registry: true
