server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://customerdbprod:5433/customerdbprod
    username: admin
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://crmdiscoveryserver:9000/eureka/
    register-with-eureka: true
    fetch-registry: true
kafka:
    producer:
      bootstrap-servers: kafka:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
